In [849]:
print("Starting PyTorch Fundamentals")

Starting PyTorch Fundamentals


In [850]:
#!nvidia-smi

In [851]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu118


**Introduction to Tensors**

Creating Tensors

PyTorch Tensors are created using *torch.tensor()*.

Basic nomenclature: 
- scalar, vector - Lower Case
- MATRIX, TENSOR - Upper Case

**Scalar**

In [852]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [853]:
# Functions
'''Checks dimension of the tensor, scalar has no dimension'''
scalar.ndim 

0

In [854]:
# Get tensor back as Python integer
scalar.item()

7

**Vector**

In [855]:
vector = torch.tensor([7,7,8])
vector

tensor([7, 7, 8])

In [856]:
vector.ndim # 1D, 1 pair of closing square brackets

1

In [857]:
vector.shape # 3 elements in vector

torch.Size([3])

**MATRIX**

In [858]:
MATRIX = torch.tensor([
    [7, 8, 10],
    [9, 6, 5] # Can't do [9, 6, 5, 4], Dimension Mismatch
])
MATRIX

tensor([[ 7,  8, 10],
        [ 9,  6,  5]])

In [859]:
MATRIX.ndim # 2D

2

In [860]:
MATRIX.shape # 2 rows, 3 columns

torch.Size([2, 3])

In [861]:
MATRIX[0] # Accessing elements

tensor([ 7,  8, 10])

In [862]:
MATRIX[1][0] # Inner access

tensor(9)

**TENSOR**

In [863]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [864]:
TENSOR.ndim

3

In [865]:
TENSOR.shape # 1 batch, 3 rows, 3 columns

torch.Size([1, 3, 3])

In [866]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [867]:
TENSOR[0][1]

tensor([4, 5, 6])

In [868]:
TENSOR[0][0]

tensor([1, 2, 3])

In [869]:
TENSOR[0][1][2] # 3D for this reason

tensor(6)

In [870]:
TENSOR2 = torch.tensor([[
    [
        [1,2,3],
        [2,3,4],
        [4,5,6]
    ],
    [
        [1,2,4],
        [3,4,7],
        [5,6,9]
    ]
]])
TENSOR2 # Same no. of elements inside each square bracket

tensor([[[[1, 2, 3],
          [2, 3, 4],
          [4, 5, 6]],

         [[1, 2, 4],
          [3, 4, 7],
          [5, 6, 9]]]])

In [871]:
TENSOR2.ndim # 4 levels of square brackets

4

In [872]:
TENSOR2.shape 
# 1 main batch, 2 sub-batches each with 3 rows and 3 columns of elements

torch.Size([1, 2, 3, 3])

In [873]:
TENSOR2

tensor([[[[1, 2, 3],
          [2, 3, 4],
          [4, 5, 6]],

         [[1, 2, 4],
          [3, 4, 7],
          [5, 6, 9]]]])

### Random Tensors

**Why random tensors?**

Random tensors are important because the way many NN learn it that they start with tensors full of random numbers and then adjust those random numbers to better represent the data. 

`Start with random variables -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

In [874]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(1, 2, 3, 4)
random_tensor

tensor([[[[0.8722, 0.9650, 0.7837, 0.8076],
          [0.0608, 0.7226, 0.3354, 0.5350],
          [0.7117, 0.7979, 0.2785, 0.8947]],

         [[0.6694, 0.8950, 0.4479, 0.4788],
          [0.3541, 0.0467, 0.7471, 0.7821],
          [0.4296, 0.1128, 0.8413, 0.4978]]]])

In [875]:
random_tensor.ndim

4

In [876]:
random_tensor.shape 
# Total number of elements: 1*2*3*4, so 24


torch.Size([1, 2, 3, 4])

In [877]:
# Create a random tensor with similar shpae to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, Color Channel
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [878]:
rand_img_tensor2 = torch.rand(224,224,4) # Works the same without using size=()
rand_img_tensor2.ndim, rand_img_tensor2.shape

(3, torch.Size([224, 224, 4]))

**Random Tensors with 1s and 0s**

In [879]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [880]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [881]:
zeros*ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [882]:
ones.dtype # Datatype

torch.float32

In [883]:
''' zeros*rand_img_tensor2 ''' # Dimension Error

' zeros*rand_img_tensor2 '

### Creating a range of tensors and tensors-like

In [884]:
# Using torch.range()
range_tensor = torch.range(2,6) # Depreciated, Goes from 2 to 6
range_tensor2 = torch.arange(5,9) # Goes from 5 to 8
range_tensor, range_tensor2

C:\Users\prash\AppData\Local\Temp\ipykernel_27804\2245269920.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(2,6) # Depreciated, Goes from 2 to 6


(tensor([2., 3., 4., 5., 6.]), tensor([5, 6, 7, 8]))

In [885]:
new_tensor = torch.arange(start=1, end=11, step=1)
new_tensor # Ends at (end - 1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [886]:
new_tensor2 = torch.arange(start=2, end=81, step=6)
new_tensor2

tensor([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80])

In [887]:
# Creating tensors like - Copying the shape
new_tensor_zeros = torch.zeros_like(input=new_tensor)
new_tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [888]:
new_tensor_ones = torch.ones_like(input=new_tensor)
new_tensor_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Dealing with tensor datatypes

**Note**: Errors faced while running PyTorch and in Deep Learning

1. Incorrect datatype
2. Incorrect Shape
3. Not on right device

In [889]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.2, 5.6, 7.8],
                               dtype=None, # Datatype float16, float32, float64
                               device='cpu', # CPU or GPU-Cuda?
                               requires_grad=False) # To track gradients or not?
float_32_tensor

tensor([3.2000, 5.6000, 7.8000])

In [890]:
float_32_tensor.dtype

torch.float32

In [891]:
dtype16_tensor = torch.tensor([3.2, 5.6, 7.8],
                            dtype=torch.float16,
                            device='cuda')
dtype16_tensor

tensor([3.1992, 5.6016, 7.8008], device='cuda:0', dtype=torch.float16)

In [892]:
dtype16_tensor.dtype

torch.float16

In [893]:
'''float_32_tensor*dtype_tensor''' # Doesn't work since 1 tensor is in CPU another in GPU

'float_32_tensor*dtype_tensor'

In [894]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor # Conversion

tensor([3.1992, 5.6016, 7.8008], dtype=torch.float16)

In [895]:
dtype32_tensor = dtype16_tensor.type(torch.float32)
dtype32_tensor

tensor([3.1992, 5.6016, 7.8008], device='cuda:0')

In [896]:
f16 = torch.tensor([1.44,2.3,3.555], dtype=torch.float16)
f32 = torch.tensor([4,5.88,6.9], dtype=torch.float32)
f64 = torch.tensor([7.3333,8.2,9.99], dtype=torch.float64)

f16, f32, f64

(tensor([1.4404, 2.3008, 3.5547], dtype=torch.float16),
 tensor([4.0000, 5.8800, 6.9000]),
 tensor([7.3333, 8.2000, 9.9900], dtype=torch.float64))

In [897]:
f16*f32, (f16*f32).dtype # Works!, changes to higher precision dtype i.e float32

(tensor([ 5.7617, 13.5286, 24.5273]), torch.float32)

In [898]:
f32*f64, f16*f64 # Works!, changes to float64

(tensor([29.3332, 48.2160, 68.9310], dtype=torch.float64),
 tensor([10.5631, 18.8664, 35.5113], dtype=torch.float64))

# Getting Tensor Attributes
## Information about Tensors

- Shape: `tensor.shape`
- Datatype: `tensor.dtype`
- Device: `tensor.device`

### Using Functions

In [899]:
some_tensor = torch.rand(3,4)
some_tensor, some_tensor.size() # Same as shape

(tensor([[0.3422, 0.6463, 0.0694, 0.4335],
         [0.3440, 0.3562, 0.0282, 0.0583],
         [0.8533, 0.9505, 0.5430, 0.8421]]),
 torch.Size([3, 4]))

In [900]:
print('Datatype: ', some_tensor.dtype)
print('Shape: ', some_tensor.shape)
print('Device: ', some_tensor.device)

Datatype:  torch.float32
Shape:  torch.Size([3, 4])
Device:  cpu


### Manipulating Tensor Attributes
#### Tensor Operations
- Addition 
- Subtraction 
- Multiplication (Element-wise)
- Division
- Matrix Multiplication 

In [901]:
atensor = torch.tensor([1,2,3])
atensor

tensor([1, 2, 3])

In [902]:
atensor + 10 # Adds 10 to all elements

tensor([11, 12, 13])

In [903]:
atensor - 5

tensor([-4, -3, -2])

In [904]:
atensor * 8

tensor([ 8, 16, 24])

In [905]:
atensor / 3

tensor([0.3333, 0.6667, 1.0000])

In [906]:
atensor // 3

tensor([0, 0, 1])

In [907]:
# PyTorch Inbuilt Functions
torch.mul(atensor, 6)

tensor([ 6, 12, 18])

In [908]:
torch.add(atensor, 5)

tensor([6, 7, 8])

### Matrix Multiplication

Two main ways of performing multiplication in NN and Deep Learning:

1. Element wise multiplication 
2. Matrix Multiplication / Dot Product

In [909]:
# Element wise Multiplication
print(atensor, '*', atensor)
print('=', (atensor*atensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
= tensor([1, 4, 9])


In [910]:
# Matrix Multiplication
torch.matmul(atensor, atensor) 
# 1*1+2*2+3*3 = 14

tensor(14)

In [911]:
%%time
value = 0
for i in range(len(atensor)):
    value += atensor[i] * atensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 998 µs


In [912]:
%%time
torch.matmul(atensor, atensor) # Vectorization

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Two main rules for performing matrix multiplication
1. The **inner dimensions** must match:
* `(3 ,2) @ (3, 2)` won't work
* `(3, 2) @ (2, 3)` works
2. The resulting matrix has the shape of the **outer dimensions**.
* `(3, 2) @ (2 ,3) -> (3, 3)`  

In [913]:
tensor_1 = torch.rand(3,2)
tensor_2 = torch.rand(3,2)
tensor_3 = torch.rand(2, 4)

In [914]:
'''torch.matmul(tensor_1, tensor_2)''' # Shape error, both (3,2)

'torch.matmul(tensor_1, tensor_2)'

In [915]:
torch.matmul(tensor_1, tensor_3) # New matrix is (3, 4)

tensor([[0.3568, 0.9743, 0.6070, 0.5910],
        [0.1139, 0.2835, 0.1585, 0.1885],
        [0.2268, 0.7316, 0.5297, 0.3765]])

### Shape Errors

In [916]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B = torch.tensor([
    [2,3],
    [5,6],
    [7,8]
])

'''torch.matmul(tensor_A, tensor_B)''' # 3 by 2 and 3 by 2

'torch.matmul(tensor_A, tensor_B)'

In [917]:
# Using Matrix Transpose: Switches axes or dimensions of a matrix
tensor_B.T, tensor_B # From 3,2 to 2,3

(tensor([[2, 5, 7],
         [3, 6, 8]]),
 tensor([[2, 3],
         [5, 6],
         [7, 8]]))

In [918]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [919]:
torch.mm(tensor_A, tensor_B.T) # Works!

tensor([[ 8, 17, 23],
        [18, 39, 53],
        [28, 61, 83]])

In [920]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Tensor Aggregation - Max, Min, Mean, Sum 


In [921]:
xtens = torch.arange(start=0, end=100, step=20)

In [922]:
xtens

tensor([ 0, 20, 40, 60, 80])

In [923]:
torch.min(xtens), xtens.min()

(tensor(0), tensor(0))

In [924]:
torch.max(xtens), xtens.max()

(tensor(80), tensor(80))

In [925]:
xtens.dtype # Mean function can't work with int64 or Long int

torch.int64

In [926]:
xtens = xtens.type(torch.float16)
xtens.mean() # Doesn't work with int

tensor(40., dtype=torch.float16)

In [927]:
torch.mean(xtens.type(torch.float64))

tensor(40., dtype=torch.float64)

In [928]:
torch.sum(xtens), xtens.sum()

(tensor(200., dtype=torch.float16), tensor(200., dtype=torch.float16))

### Finding positional min and max
Index of minimum and maximum

- `tensor.argmin()` -> Returns index position of target tensor where minimum value occurs
- `tensor.argmax()` -> Returns index position of target tensor where maximum value occurs, needed later on for Softmax function

In [929]:
xtens.argmin(), xtens.argmax()

(tensor(0), tensor(4))

In [930]:
ytens = torch.rand(1,2,3,4)

In [931]:
ytens

tensor([[[[0.0168, 0.8506, 0.5325, 0.4284],
          [0.0743, 0.0911, 0.6694, 0.1401],
          [0.4400, 0.7214, 0.8828, 0.2290]],

         [[0.3566, 0.6354, 0.6072, 0.8164],
          [0.9520, 0.7464, 0.9612, 0.5058],
          [0.2447, 0.3062, 0.5583, 0.9522]]]])

In [932]:
ytens.mean()

tensor(0.5299)

In [933]:
ytens.max()

tensor(0.9612)

In [934]:
ytens[0][1].max() # Index wise aggregation too

tensor(0.9612)

In [935]:
ytens[0][1][1].min(), ytens[0][1][1].mean()

(tensor(0.5058), tensor(0.7913))

## Reshaping, Stacking, Squeezing and Unsqueezing Tensors
- **Reshaping** - Reshapes an input tensor to a defined tensor
- **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- **Stacking** - Combine multiple tensors on top of each each (vstack) or side by side (hstack)
- **Squeeze** - Removes all `1` dimensions from a tensor
- **Unsqueeze** - Add a `1` dimension to a target tensor
- **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [936]:
ztens = torch.arange(0, 100, 5)
ztens, ztens.shape

(tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
         90, 95]),
 torch.Size([20]))

In [937]:
# Add an extra dimension - 1 more square bracket
ztens_reshaped = ztens.reshape(1, 20) # 1 row, 20 cols
ztens_reshaped, ztens_reshaped.shape

(tensor([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
          90, 95]]),
 torch.Size([1, 20]))

In [938]:
ztens_reshaped_2 = ztens.reshape(20, 1) # 20 rows, 1 col
ztens_reshaped_2, ztens_reshaped_2.shape 

(tensor([[ 0],
         [ 5],
         [10],
         [15],
         [20],
         [25],
         [30],
         [35],
         [40],
         [45],
         [50],
         [55],
         [60],
         [65],
         [70],
         [75],
         [80],
         [85],
         [90],
         [95]]),
 torch.Size([20, 1]))

In [939]:
# Original shape is 20 so can be reshaped into combinations that yield 20 when multiplied
ztens_reshap_3 = ztens.reshape(2, 5, 2) # (2, 10), (4, 5)
ztens_reshap_3, ztens_reshap_3.shape

(tensor([[[ 0,  5],
          [10, 15],
          [20, 25],
          [30, 35],
          [40, 45]],
 
         [[50, 55],
          [60, 65],
          [70, 75],
          [80, 85],
          [90, 95]]]),
 torch.Size([2, 5, 2]))

In [940]:
# Change the view
z = ztens.view(2,5,2)
z, z.shape

(tensor([[[ 0,  5],
          [10, 15],
          [20, 25],
          [30, 35],
          [40, 45]],
 
         [[50, 55],
          [60, 65],
          [70, 75],
          [80, 85],
          [90, 95]]]),
 torch.Size([2, 5, 2]))

### Changing `z` change `ztens` because a view of a tensor shares the same memory as the original input

In [941]:
z[0][0][0] = 66
z, ztens # First element of both tensors changed

(tensor([[[66,  5],
          [10, 15],
          [20, 25],
          [30, 35],
          [40, 45]],
 
         [[50, 55],
          [60, 65],
          [70, 75],
          [80, 85],
          [90, 95]]]),
 tensor([66,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
         90, 95]))

In [942]:
z[:, 0] = 33 # Changes all elements at 0th index of all batches to 33
z, ztens

(tensor([[[33, 33],
          [10, 15],
          [20, 25],
          [30, 35],
          [40, 45]],
 
         [[33, 33],
          [60, 65],
          [70, 75],
          [80, 85],
          [90, 95]]]),
 tensor([33, 33, 10, 15, 20, 25, 30, 35, 40, 45, 33, 33, 60, 65, 70, 75, 80, 85,
         90, 95]))

In [943]:
# Stack tensors on top of each other
btens = torch.arange(5, 70, 5)
btens.shape
btens, btens.reshape(13, 1)


(tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65]),
 tensor([[ 5],
         [10],
         [15],
         [20],
         [25],
         [30],
         [35],
         [40],
         [45],
         [50],
         [55],
         [60],
         [65]]))

In [944]:
b_stacked0 = torch.stack([btens, btens, btens], dim=0) # Row Stacking
b_stacked0

tensor([[ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65],
        [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65],
        [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65]])

In [945]:
b_stacked1 = torch.stack([btens, btens, btens], dim=1) # Column Stacking
b_stacked1

tensor([[ 5,  5,  5],
        [10, 10, 10],
        [15, 15, 15],
        [20, 20, 20],
        [25, 25, 25],
        [30, 30, 30],
        [35, 35, 35],
        [40, 40, 40],
        [45, 45, 45],
        [50, 50, 50],
        [55, 55, 55],
        [60, 60, 60],
        [65, 65, 65]])

In [946]:
# Squeezing and Unsqueezing
ctens = torch.zeros(1,2,1,4)
print(f'Original ctens: {ctens}')
print(f"Original ctens shape: {ctens.shape}")

Original ctens: tensor([[[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]]])
Original ctens shape: torch.Size([1, 2, 1, 4])


In [947]:
print(f"Squeezed ctens: {torch.squeeze(ctens)}") # Less square brackets
print(f"Shape of squeezed ctens: {torch.squeeze(ctens).shape}") # Removes all 1 dims / extra dims

Squeezed ctens: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape of squeezed ctens: torch.Size([2, 4])


In [948]:
dtens = torch.rand(2,3,4)
print(f'Original dtens: {dtens}')
print(f'Shape of original dtens: {dtens.shape}')

Original dtens: tensor([[[0.4855, 0.6646, 0.1143, 0.8907],
         [0.3764, 0.6323, 0.3431, 0.0253],
         [0.4094, 0.5202, 0.1545, 0.5854]],

        [[0.0350, 0.1388, 0.6834, 0.7266],
         [0.3758, 0.8598, 0.1552, 0.1022],
         [0.1558, 0.7550, 0.6614, 0.5982]]])
Shape of original dtens: torch.Size([2, 3, 4])


In [949]:
# torch.unsqueeze() - Adds single dimension to target tensor at a specific dimension
rng = 1
for i in range(0,rng):
    dtens_unsqueezed = dtens.unsqueeze(dim=i) 
    # `dim=0` Existing dimension where single dimension is added
    print(f'Unsqueezed dtens when `dim` = {i}: {dtens_unsqueezed}')
    print(f'Shape of unsqueezed dtens when `dim` = {i}: {dtens_unsqueezed.shape}\n')

Unsqueezed dtens when `dim` = 0: tensor([[[[0.4855, 0.6646, 0.1143, 0.8907],
          [0.3764, 0.6323, 0.3431, 0.0253],
          [0.4094, 0.5202, 0.1545, 0.5854]],

         [[0.0350, 0.1388, 0.6834, 0.7266],
          [0.3758, 0.8598, 0.1552, 0.1022],
          [0.1558, 0.7550, 0.6614, 0.5982]]]])
Shape of unsqueezed dtens when `dim` = 0: torch.Size([1, 2, 3, 4])



In [950]:
# Permutation - Swap dimension position, it's a view - shares same memory as original input tensor
etens = torch.rand(222,224,3) # Image Tensor
print(f'Shape of Original etens: {etens.shape}')

etens_permute = etens.permute(1, 2, 0) 
# Shifts axis 0->2, 1->0, 2->1
print(f'Shape of Permuted etens: {etens_permute.shape}')

etens


Shape of Original etens: torch.Size([222, 224, 3])
Shape of Permuted etens: torch.Size([224, 3, 222])


tensor([[[0.6728, 0.0603, 0.6815],
         [0.2306, 0.2800, 0.7685],
         [0.1743, 0.6163, 0.1643],
         ...,
         [0.7810, 0.3440, 0.2457],
         [0.9067, 0.6191, 0.1211],
         [0.6532, 0.5918, 0.8413]],

        [[0.9169, 0.3164, 0.3975],
         [0.6474, 0.5463, 0.5337],
         [0.6289, 0.8412, 0.8646],
         ...,
         [0.3038, 0.0922, 0.9058],
         [0.1338, 0.7756, 0.2752],
         [0.6557, 0.8337, 0.4600]],

        [[0.1691, 0.5389, 0.6808],
         [0.8711, 0.1514, 0.0334],
         [0.6186, 0.5743, 0.8249],
         ...,
         [0.3504, 0.1944, 0.3149],
         [0.2861, 0.8190, 0.0076],
         [0.0194, 0.1645, 0.2291]],

        ...,

        [[0.1991, 0.4650, 0.6778],
         [0.9613, 0.0918, 0.5338],
         [0.4334, 0.1183, 0.6962],
         ...,
         [0.2737, 0.5545, 0.2927],
         [0.1775, 0.9241, 0.8708],
         [0.4036, 0.7623, 0.9566]],

        [[0.4805, 0.5964, 0.5469],
         [0.0637, 0.3955, 0.2255],
         [0.

In [951]:
print(etens[0, 0, 0] == etens[0][0][0])
etens[0, 0, 0], etens[0][0][0]

tensor(True)


(tensor(0.6728), tensor(0.6728))

In [952]:
etens[0, 0, 0] == etens_permute[0, 0, 0] # View so shares same memory

tensor(True)

In [953]:
print(f'etens value at loc: {etens[0, 0, 0]}')
print(f'etens_permute at loc: {etens_permute[0, 0, 0]}')

etens value at loc: 0.6728498935699463
etens_permute at loc: 0.6728498935699463


In [954]:
etens[1, 1, 1] = 0.9778877 # Changing value at specific location

print(f'etens value at loc: {etens[1, 1, 1]}')
print(f'etens_permute at loc: {etens_permute[1, 1, 1]}')

# Since, the tensors are permuted only elements at [i, i, i] index are same

etens value at loc: 0.9778876900672913
etens_permute at loc: 0.9778876900672913


### Indexing - Selecting data from tensors

Indexing with PyTorch is similar to indexing with Numpy

In [955]:
new_tens = torch.arange(1, 10).reshape(1, 3, 3)
new_tens, new_tens.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [956]:
# Indexing
new_tens[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [957]:
new_tens[0][1] == new_tens[0, 1]

tensor([True, True, True])

In [958]:
new_tens[0][0][0], new_tens[0, 1, 0]

(tensor(1), tensor(4))

In [959]:
new_tens[0, 2, 2]

tensor(9)

In [960]:
# Get all values of a target dimension
new_tens[:, 0]

tensor([[1, 2, 3]])

In [961]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
new_tens[:, :, 1]

tensor([[2, 5, 8]])

In [962]:
# Get all values of 0 dimension and index 1 of 1st and 2nd dimension
new_tens[:, 1, 1]

tensor([5])

In [963]:
new_tens[0, 0, :]

tensor([1, 2, 3])

In [964]:
new_tens

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [965]:
new_tens[:, :, 1]

tensor([[2, 5, 8]])

In [966]:
new_tens[:] # 3 Layers of Square Brackets

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [967]:
new_tens[0] # Only 2 Layers of Square Brackets

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [968]:
new_tens[:, :, 2], new_tens[:, 2], new_tens[:, 2, 2]

(tensor([[3, 6, 9]]), tensor([[7, 8, 9]]), tensor([9]))

### PyTorch Tensors and NumPy

NumPy is a popular scientific python numerical computing library.

And because of this, PyTorch has functionality to interact with it. 

- Data in NumPy into PyTorch Tensor -> `torch.from_numpy(ndarray)`
- PyTorch Tensor into NumPy -> `torch.Tensor.numpy()`

**NumPy Array to PyTorch Tensor**

In [969]:
import numpy as np 

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

print(f'Numpy Array: {array}')
print(f'PyTorch Tensor: {tensor}')

Numpy Array: [1. 2. 3. 4. 5. 6. 7.]
PyTorch Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [970]:
# Datatype of NumPy Array and PyTorch Tensor
arrayx = np.arange(1.0, 8.0)
tensx = torch.arange(1.0, 8.0)

arrayx.dtype, tensx.dtype # Default dtypes

''' When converting from Tensor to Array, dtype changes to float64 '''

' When converting from Tensor to Array, dtype changes to float64 '

In [971]:
# Changing dtypes while changing from Array to Tensor
array2tens = torch.from_numpy(arrayx).type(torch.float32)
array2tens, array2tens.dtype # Keeps dtype as float32 

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

**PyTorch Tensor to NumPy Array**

In [972]:
tensx = torch.arange(1.0, 9.0) # Default dtype of tensor is float32
ndarray = tensx.numpy() # Default dtype numpy is float64

print(f'PyTorch Tensor: {tensx} and Dtype is {tensx.dtype}') 
print(f'Numpy Array: {ndarray} and Dtype is {ndarray.dtype}')

''' NumPy array produced by converting PyTorch Tensor will have float32 as dtype '''

PyTorch Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.]) and Dtype is torch.float32
Numpy Array: [1. 2. 3. 4. 5. 6. 7. 8.] and Dtype is float32


' NumPy array produced by converting PyTorch Tensor will have float32 as dtype '

### PyTorch Reproducibility - Taking away Randomness

In [973]:
torch.rand(3, 3) # Different values for each execution

tensor([[0.0901, 0.3984, 0.9304],
        [0.5401, 0.6983, 0.7667],
        [0.0403, 0.1155, 0.0231]])

In [974]:
torch.rand(3,3) == torch.rand(3,3) # Nearly always False

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [975]:
# Set a random seed

RANDOM_SEED = 44
torch.manual_seed(RANDOM_SEED) 
# Seeds need to set before creation of every new random tensor
ptens = torch.rand(3, 3)

torch.manual_seed(RANDOM_SEED)
qtens = torch.rand(3, 3)

print(f"ptens: {ptens}")
print(f"qtens: {qtens}")

print(ptens == qtens)

ptens: tensor([[0.7196, 0.7307, 0.8278],
        [0.1343, 0.6280, 0.7297],
        [0.2882, 0.2112, 0.9836]])
qtens: tensor([[0.7196, 0.7307, 0.8278],
        [0.1343, 0.6280, 0.7297],
        [0.2882, 0.2112, 0.9836]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Running Tensors and PyTorch objects on the GPUs

- Faster computations, due to CUDA + NVIDIA Hardware

In [976]:
!nvidia-smi

Sun May  4 15:41:49 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.83                 Driver Version: 572.83         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   44C    P8              1W /   88W |    1916MiB /   8188MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Setup Device Agnostic Code

In [977]:
# Setup Devices
device = "cuda" if torch.cuda.is_available() else "cpu"
device 

'cuda'

In [978]:
# Count the numbers
torch.cuda.device_count()

1

### Putting Tensors and Models on the GPU for faster computations

In [979]:
cp_tens = torch.tensor([1,2,3])
cp_tens, cp_tens.device # On CPU by default

(tensor([1, 2, 3]), device(type='cpu'))

In [980]:
# Move tensor to GPU if available
gp_tens = cp_tens.to(device)
gp_tens, gp_tens.device # Index 0 - GPU Count

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [981]:
# If tensor is on GPU, can't convert to NumPy since it only works on CPU
''' gp_tens.numpy() -> Error '''

' gp_tens.numpy() -> Error '

In [982]:
cp_tens_2 = gp_tens.cpu() # Move back to CPU for NumPy Conversion
cp_tens_2.numpy()

array([1, 2, 3])

`pytorch.io` for Exercises and Extra Curriculum